package store

import (
	"log"
	"sync"
	"time"

	"github.com/umputun/secrets/app/crypt"
)

// InMemory implements store.Interface with concurent map
type InMemory struct {
	messageProc
	sync.Mutex
	data map[string]Message
}

// NewInMemory makes new store with max duration
func NewInMemory(crypt crypt.Crypt, maxDuration time.Duration) *InMemory {
	result := InMemory{
		data:        map[string]Message{},
		messageProc: messageProc{maxDuration: maxDuration, Crypt: crypt},
	}
	result.activateCleaner()
	return &result
}

// Save to map with autogenerated uuid as a key
func (s *InMemory) Save(duration time.Duration, msg string, pin string) (result *Message, err error) {

	result, err = s.MakeMessage(duration, msg, pin)
	if err != nil {
		log.Printf("[WARN] can't save. failed to make message, %v", err)
		return nil, ErrSaveRejected
	}

	s.Lock()
	defer s.Unlock()

	s.data[result.Key] = *result
	log.Printf("[DEBUG] saved %s... (%v), total %d", result.Key[:6], result.Exp, len(s.data))
	return result, nil
}

// Load by key, removes on first access, checks expire
func (s *InMemory) Load(key string, pin string) (result *Message, err error) {

	remove := func(key string) {
		delete(s.data, key)
		log.Printf("[DEBUG] removed %s", key)
	}

	s.Lock()
	defer s.Unlock()
	msg, ok := s.data[key]

	if !ok {
		log.Printf("[INFO] not found %s", key)
		return nil, ErrGetRejected
	}

	result, err = s.FromMessage(msg, pin)
	if err == ErrBadPinAttempt {
		s.data[key] = *result
		return nil, ErrBadPin
	}

	if err != nil {
		remove(key)
		return nil, ErrGetRejected
	}

	remove(key)
	return result, nil

}

func (s *InMemory) activateCleaner() {
	log.Print("[INFO] activate cleaner")

	ticker := time.NewTicker(time.Minute * 5)
	go func() {
		for t := range ticker.C {
			s.Lock()
			for k, v := range s.data {
				if v.Exp.After(time.Now()) {
					delete(s.data, k)
					log.Printf("[INFO] cleaned %s on %v", k, t)
				}
			}
			s.Unlock()
		}
	}()
}
