// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/secrets/app/email"
)

// EmailSenderMock is a mock implementation of server.EmailSender.
//
//	func TestSomethingThatUsesEmailSender(t *testing.T) {
//
//		// make and configure a mocked server.EmailSender
//		mockedEmailSender := &EmailSenderMock{
//			GetDefaultFromNameFunc: func() string {
//				panic("mock out the GetDefaultFromName method")
//			},
//			SendFunc: func(ctx context.Context, req email.Request) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedEmailSender in code that requires server.EmailSender
//		// and then make assertions.
//
//	}
type EmailSenderMock struct {
	// GetDefaultFromNameFunc mocks the GetDefaultFromName method.
	GetDefaultFromNameFunc func() string

	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, req email.Request) error

	// calls tracks calls to the methods.
	calls struct {
		// GetDefaultFromName holds details about calls to the GetDefaultFromName method.
		GetDefaultFromName []struct {
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req email.Request
		}
	}
	lockGetDefaultFromName sync.RWMutex
	lockSend               sync.RWMutex
}

// GetDefaultFromName calls GetDefaultFromNameFunc.
func (mock *EmailSenderMock) GetDefaultFromName() string {
	if mock.GetDefaultFromNameFunc == nil {
		panic("EmailSenderMock.GetDefaultFromNameFunc: method is nil but EmailSender.GetDefaultFromName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDefaultFromName.Lock()
	mock.calls.GetDefaultFromName = append(mock.calls.GetDefaultFromName, callInfo)
	mock.lockGetDefaultFromName.Unlock()
	return mock.GetDefaultFromNameFunc()
}

// GetDefaultFromNameCalls gets all the calls that were made to GetDefaultFromName.
// Check the length with:
//
//	len(mockedEmailSender.GetDefaultFromNameCalls())
func (mock *EmailSenderMock) GetDefaultFromNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDefaultFromName.RLock()
	calls = mock.calls.GetDefaultFromName
	mock.lockGetDefaultFromName.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *EmailSenderMock) Send(ctx context.Context, req email.Request) error {
	if mock.SendFunc == nil {
		panic("EmailSenderMock.SendFunc: method is nil but EmailSender.Send was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req email.Request
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, req)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedEmailSender.SendCalls())
func (mock *EmailSenderMock) SendCalls() []struct {
	Ctx context.Context
	Req email.Request
} {
	var calls []struct {
		Ctx context.Context
		Req email.Request
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
