version: '2'
services:

    secrets:
        build: .
        image: umputun/secrets:latest
        container_name: secrets
        hostname: secrets
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./var:/data

        environment:
           - SIGN_KEY=change-this-to-smth-random
           - ENGINE=MEMORY
           - PIN_SIZE=5
           - BOLT_FILE=/data/secrets.bd
           - PIN_ATTEMPTS=3
           - MAX_EXPIRE=86400

    nginx:
        build: nginx
        image: umputun/secrets:nginx
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        depends_on:
            - secrets

        volumes:
            - ./etc/ssl:/etc/nginx/ssl

        volumes_from:
            - secrets

        ports:
            - "80:80"
            - "443:443"

        environment:
            - LETSENCRYPT=false
            - LE_EMAIL=name@example.com
            - LE_FQDN=www.example.com

            - SSL_CERT=secrets-crt.pem
            - SSL_KEY=secrets-key.pem
