FROM alpine:3.4

# add user and set TZ
RUN \
 apk add --update tzdata && \
 adduser -s /bin/bash -D -u 1001 secrets && \
 mkdir -p /srv && chown -R secrets:secrets /srv && \
 cp /usr/share/zoneinfo/America/Chicago /etc/localtime && \
 echo "America/Chicago" > /etc/timezone && \
 rm -rf /var/cache/apk/*

ADD target/secrets /srv/secrets
RUN chmod +x /srv/secrets

ADD target/docroot /srv/docroot

EXPOSE 8080
USER secrets
WORKDIR /srv

VOLUME ["/srv/docroot"]
ENTRYPOINT ["/srv/secrets"]
