### save message

POST http://localhost:8080/api/v1/message
Content-Type: application/json

{
    "message": "my secret message",
    "exp": 600,
    "pin": "12345"
}

### get message
GET http://localhost:8080/api/v1/message/1532232191-0e4a988b-d017-49f3-51db-015510ba5e1a/12345

### get params
http://localhost:8080/api/v1/params