({
	block: 'document',
	title: 'SafeSecret.Info',
	styles: ['../css/main.css'],
	scripts: ['../js/main.js'],
	content: [
		{
			block: 'fs-form',
			attrs: {
				id: 'fs-form'
			},
			content: [
				{
					block: 'header',
					content: {
						block: 'link',
						url: '/',
						content: 'SafeSecret.Info'
					}
				},
				{
					elem: 'content',
					elemMods: { full: true },
					tag: 'form',
					attrs: {
						autocomplete: 'off'
					},
					content: [
						{
							block: 'fields',
							content: [
								{
									block: 'field',
									id: 'pin',
									title: 'Enter the secret PIN to see content',
									content: {
										block: 'input',
										mods: { type: 'pin' },
										id: 'pin',
										placeholder: '5-digit PIN'
									}
								}
							]
						},
						{
							block: 'result',
							content: [
								{
									elem: 'throbber',
									content: 'Loading..'
								},
								{
									elem: 'tip',
									attrs: {
										id: 'result__tip'
									}
								},
								{
									block: 'link',
									mix: { block: 'result', elem: 'again' },
									url: 'javascript:location.reload()',
									content: 'Try again'
								},
								{
									block: 'link',
									mix: { block: 'result', elem: 'to-main' },
									url: '/',
									content: 'Back to main page'
								},
								{
									block: 'textarea',
									mods: { result: true },
									mix: { block: 'result', elem: 'info' },
									attrs: {
										id: 'result__info'
									}
								},
								{
									block: 'description',
									mix: { block: 'result', elem: 'desc' },
									content: 'This information will self-destruct after you close this page.'
								},
								{
									block: 'button',
									mods: { content: 'copy', shown: true },
									mix: { block: 'result', elem: 'button' },
									attrs: {
										'data-clipboard-target': '#result__info'
									},
									content: 'Copy'
								},
							]
						}
					]
				}
			]
		},
		{
			block: 'popup',
			attrs: {
				id: 'welcome'
			},
			content: 'SafeSecret is a simple service made for a single purpose: sharing confidential information in an easy, quick and secure way. Think of it as writing a paper note, letting someone read it, then burning it. Simply type or paste any text into SafeSecret, define for how long you’d like the information to be accessible, and create a 5-digit PIN. Then, copy the link generated by SafeSecret and share it with someone in any way you’d like. Once the link is opened with the input of your 5-digit PIN, it can never be opened or seen again — the information self-destructs without a trace.'
		}
	]
})
