package store

import (
	"log"
	"sync"
	"time"
)

// InMemory implements store.Interface with concurrent map
type InMemory struct {
	sync.Mutex
	data map[string]Message
}

// NewInMemory makes new store with max duration
func NewInMemory(cleanupDuration time.Duration) *InMemory {
	log.Print("[INFO] in-memory (ephemeral) store")
	result := InMemory{data: map[string]Message{}}
	result.activateCleaner(cleanupDuration)
	return &result
}

// Save to map with autogenerated uuid as a key
func (s *InMemory) Save(msg *Message) (err error) {

	s.Lock()
	defer s.Unlock()

	s.data[msg.Key] = *msg
	log.Printf("[DEBUG] saved, exp=%v, total %d", msg.Exp, len(s.data))
	return nil
}

// Load by key, removes on first access, checks expire
func (s *InMemory) Load(key string) (result *Message, err error) {

	s.Lock()
	defer s.Unlock()
	msg, ok := s.data[key]

	if !ok {
		log.Printf("[INFO] not found %s", key)
		return nil, ErrLoadRejected
	}

	return &msg, nil
}

// IncErr increments error count
func (s *InMemory) IncErr(key string) (count int, err error) {
	s.Lock()
	defer s.Unlock()
	msg, ok := s.data[key]

	if !ok {
		log.Printf("[INFO] not found %s", key)
		return 0, ErrLoadRejected
	}
	msg.Errors++
	s.data[key] = msg
	return msg.Errors, nil
}

// Remove by key
func (s *InMemory) Remove(key string) (err error) {
	s.Lock()
	defer s.Unlock()
	delete(s.data, key)
	log.Printf("[DEBUG] removed %s", key)
	return nil
}

// activateCleaner runs periodic cleanups to get rid or expired msgs
func (s *InMemory) activateCleaner(every time.Duration) {
	log.Printf("[INFO] cleaner activated, every %v", every)

	ticker := time.NewTicker(every)
	go func() {
		for range ticker.C {
			s.Lock()
			for k, v := range s.data {
				if v.Exp.Before(time.Now()) {
					delete(s.data, k)
					log.Printf("[INFO] cleaned %s", k)
				}
			}
			s.Unlock()
		}
	}()
}
