// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// NotifierMock is a mock implementation of email.Notifier.
//
//	func TestSomethingThatUsesNotifier(t *testing.T) {
//
//		// make and configure a mocked email.Notifier
//		mockedNotifier := &NotifierMock{
//			SendFunc: func(ctx context.Context, destination string, text string) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedNotifier in code that requires email.Notifier
//		// and then make assertions.
//
//	}
type NotifierMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(ctx context.Context, destination string, text string) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Destination is the destination argument value.
			Destination string
			// Text is the text argument value.
			Text string
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *NotifierMock) Send(ctx context.Context, destination string, text string) error {
	if mock.SendFunc == nil {
		panic("NotifierMock.SendFunc: method is nil but Notifier.Send was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Destination string
		Text        string
	}{
		Ctx:         ctx,
		Destination: destination,
		Text:        text,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(ctx, destination, text)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedNotifier.SendCalls())
func (mock *NotifierMock) SendCalls() []struct {
	Ctx         context.Context
	Destination string
	Text        string
} {
	var calls []struct {
		Ctx         context.Context
		Destination string
		Text        string
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
