// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messager

import (
	"context"
	"sync"

	"github.com/umputun/secrets/v2/app/store"
)

// Ensure, that EngineMock does implement Engine.
// If this is not the case, regenerate this file with moq.
var _ Engine = &EngineMock{}

// EngineMock is a mock implementation of Engine.
//
//	func TestSomethingThatUsesEngine(t *testing.T) {
//
//		// make and configure a mocked Engine
//		mockedEngine := &EngineMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			IncErrFunc: func(ctx context.Context, key string) (int, error) {
//				panic("mock out the IncErr method")
//			},
//			LoadFunc: func(ctx context.Context, key string) (*store.Message, error) {
//				panic("mock out the Load method")
//			},
//			RemoveFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Remove method")
//			},
//			SaveFunc: func(ctx context.Context, msg *store.Message) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedEngine in code that requires Engine
//		// and then make assertions.
//
//	}
type EngineMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// IncErrFunc mocks the IncErr method.
	IncErrFunc func(ctx context.Context, key string) (int, error)

	// LoadFunc mocks the Load method.
	LoadFunc func(ctx context.Context, key string) (*store.Message, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, key string) error

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, msg *store.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// IncErr holds details about calls to the IncErr method.
		IncErr []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Load holds details about calls to the Load method.
		Load []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg *store.Message
		}
	}
	lockClose  sync.RWMutex
	lockIncErr sync.RWMutex
	lockLoad   sync.RWMutex
	lockRemove sync.RWMutex
	lockSave   sync.RWMutex
}

// Close calls CloseFunc.
func (mock *EngineMock) Close() error {
	if mock.CloseFunc == nil {
		panic("EngineMock.CloseFunc: method is nil but Engine.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedEngine.CloseCalls())
func (mock *EngineMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// IncErr calls IncErrFunc.
func (mock *EngineMock) IncErr(ctx context.Context, key string) (int, error) {
	if mock.IncErrFunc == nil {
		panic("EngineMock.IncErrFunc: method is nil but Engine.IncErr was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockIncErr.Lock()
	mock.calls.IncErr = append(mock.calls.IncErr, callInfo)
	mock.lockIncErr.Unlock()
	return mock.IncErrFunc(ctx, key)
}

// IncErrCalls gets all the calls that were made to IncErr.
// Check the length with:
//
//	len(mockedEngine.IncErrCalls())
func (mock *EngineMock) IncErrCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockIncErr.RLock()
	calls = mock.calls.IncErr
	mock.lockIncErr.RUnlock()
	return calls
}

// Load calls LoadFunc.
func (mock *EngineMock) Load(ctx context.Context, key string) (*store.Message, error) {
	if mock.LoadFunc == nil {
		panic("EngineMock.LoadFunc: method is nil but Engine.Load was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(ctx, key)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedEngine.LoadCalls())
func (mock *EngineMock) LoadCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *EngineMock) Remove(ctx context.Context, key string) error {
	if mock.RemoveFunc == nil {
		panic("EngineMock.RemoveFunc: method is nil but Engine.Remove was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(ctx, key)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedEngine.RemoveCalls())
func (mock *EngineMock) RemoveCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *EngineMock) Save(ctx context.Context, msg *store.Message) error {
	if mock.SaveFunc == nil {
		panic("EngineMock.SaveFunc: method is nil but Engine.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg *store.Message
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, msg)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedEngine.SaveCalls())
func (mock *EngineMock) SaveCalls() []struct {
	Ctx context.Context
	Msg *store.Message
} {
	var calls []struct {
		Ctx context.Context
		Msg *store.Message
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
